/* Generated By:JavaCC: Do not edit this line. JaggerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JaggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int LB = 8;
  /** RegularExpression Id. */
  int RB = 9;
  /** RegularExpression Id. */
  int PRINT = 10;
  /** RegularExpression Id. */
  int EOL = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "<VARIABLE>",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"print\"",
    "\"\\n\"",
    "\"==\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
