/* Generated By:JavaCC: Do not edit this line. JaggerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JaggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINT = 4;
  /** RegularExpression Id. */
  int LRB = 5;
  /** RegularExpression Id. */
  int RRB = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int THEN = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int LET = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int EOL = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int VARIABLE = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\",\"",
    "\"var\"",
    "\":=\"",
    "\"\\n\"",
    "<NUMBER>",
    "<STRING>",
    "<DIGIT>",
    "<VARIABLE>",
    "\"==\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
